### ISSUE TITLE
literadar WARNING smali code is None.

### ISSUE THREAD

**Issue by zacharykzhao** [E0HYL/MsDroid#2]
When I run the code in my dataset, billions of warning gives: samli code is None. 
May I have your suggestions? Thanks in advance.

**Comment by E0HYL** [comment]
Hi, this is an [output from literadar](https://github.com/E0HYL/MsDroid/blob/29bb64bdbac68eb0458ed298e5f612769fe92e69/src/feature/LibRadar/Data/literadar.py#L146) which is used in MsDroid to detect third party libraries (TPLs).
It seems that the tool failed to parse any instructions from the dexfile. You may check the tool seperately following the instructions in its [original repo](https://github.com/pkumza/LiteRadar/blob/master/docs/QuickStart.md).
To speed up the extraction of TPLs, you may want to refer to [another repo of mine](https://github.com/E0HYL/AI4Code-Framework/tree/main/ai4code/features/preprocessing/androguard_literadar) which integrates the parser with androguard framework (not fully tested).
Furthermore, it might be acceptable to disable the TPL detection process during pre-processing and simply treat them as nodes in $S_{usr}$ (see details in the paper). It may degrade the accuracy to some extent but reduce the time cost.

**Comment by zacharykzhao** [comment]
Thank you very much for your help and answers. May I have your suggestion how to configure the settings  if I want to disable TPL detection process? 
The default settings (True of '--tpl' in _train.py_ ) will give the libradar warning.
When I set the value ('--tpl' in _train.py_) as False the error still occurs.
Thank you very much for your time and help!

**Comment by E0HYL** [comment]
Hi, the `--tpl` option in `train.py` is not used to disable TPL detection process. It was originally designed for part of the *Reduction* step in *Subgraph Set Generation* (Section 3.2.1 in the paper).
If you want to totally disable this process, you may want to modify the code [here](https://github.com/E0HYL/MsDroid/blob/29bb64bdbac68eb0458ed298e5f612769fe92e69/src/feature/Andro/Andro.py#L142).
And there is another option to speed up the process, i.e., set [`--deepth`](https://github.com/E0HYL/MsDroid/blob/29bb64bdbac68eb0458ed298e5f612769fe92e69/src/train.py#L37) to a smaller number as it controls the DFS depth for feature generation of nodes in $S_{tpl}$. But to handle the warning from LiteRadar, you must check that the tool works properly first.
