### ISSUE TITLE
Data Preprocesing

### ISSUE THREAD

**Issue by Rroscha** [E0HYL/MsDroid#3]
Hello! I'm interesting your MSDROID and have downloaded your code and run it, but I encounter a problem. The data preprocessing is too time  consuming. I prepared 34 apk samples for training, but at the data preprocessing stage, I take nearly 3 hours for it. I'm so confused on it and wonder may be the parameters I setting are erroneous.

The time I start.
![image](https://user-images.githubusercontent.com/70827525/190892408-f476af4c-0a8c-448a-8030-c9734a52dd7b.png)

Until now, still unfinished.
![image](https://user-images.githubusercontent.com/70827525/190892437-3d78e5da-db76-4a2e-a422-8cf12b267e77.png)

**Comment by E0HYL** [comment]
Hi, thanks for your interest.
The logic of analyzing an APP is implemented in [`analysis_app`](https://github.com/E0HYL/MsDroid/blob/8f1fad5b7785c69e86bc02890fa53d5782997001/src/feature/Andro/Andro.py#L56). You can debug here which step costs the most for your dataset. For issues related to TPL detection, you may want to refer to #2.

**Comment by Rroscha** [comment]
OK, thanks. I'll check it later. Oh! I have another two question, how do I set labels for training and test samples, and what's the sepecific meaning of the parameter "--dbs" in train.py?

**Comment by E0HYL** [comment]
> OK, thanks. I'll check it later. Oh! I have another two question, how do I set labels for training and test samples, and what's the sepecific meaning of the parameter "--dbs" in train.py?

APPs in the same directory have the same label in my setting, so the db names are named after directory names. Labels are set when you generate behavior subgraphs for individual directories.
To understand that, you can read the code [here](https://github.com/E0HYL/MsDroid/blob/8f1fad5b7785c69e86bc02890fa53d5782997001/src/graph/behavior_subgraph.py#L35).
Feel free to modify this setting at your own convenience.

**Comment by Rroscha** [comment]
Ok! Thanks so much.
